### ISSUE TITLE
FEATURE - Introduce "View All" view to Blogs filters

### ISSUE THREAD

**Issue by cjbernal** [SAP/knowledge-hub-extension#33]
_As a **developer looking for specific content in the blogs tab of knowledge hub**,
I want to **see all of the filters available to me**,
so that I **can better understand the different topics I can read about**_

### Description

_blogs.sap.com has a `View all` feature that allows users to see all of the tags that exist on the platform. In order to create feature parity with the site and help users understand the wide variety of topics available to them, we should also introduce similar functionality: https://blogs.sap.com/tags/._ The tags are searchable and update based on the users current input. 

### Technical Design
_What modules need to be created or enhanced?_ 
_How would the functionality be exposed and how can it be consumed?_

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have the filter interface open in the Blogs tab ...
**when** I click the `View all` button ...
**then** all of the tags available on blogs.sap.com should be viewable in a pop-up
and I should be able to search for existing tags
and I should be able to select a tag and go back to the blog tab
and then I should be able to click `View All` again and select another tag in addition if required.

### Tasks
- [ ] Create a new tag page -- 2 days
- [ ] Update routing for clicking tags -- 2 days
- [ ] Unit Tests added -- 2 days
- [ ] Test Cases defined

**Comment by eouin** [comment]
@gpeuc We will need some design for that story

**Comment by cjbernal** [comment]
This is present and tested in the latest version. Closing this.
