### ISSUE TITLE
TBI - Provide telemetry data for the tutorials and tutorial tags opened

### ISSUE THREAD

**Issue by cjbernal** [SAP/knowledge-hub-extension#35]
### Description (include screenshots)
In order to better understand the content our users access with the knowledge hub, we should be able to see the tutorial cards and primary tags opened by our users. A tutorial (and its primary tag) should only be recorded if the user clicks on the card and opens the tutorial in the browser. This will help us to better understand the topics that are of interest to our users. 

No user data should be recorded. 

### Architecture Elaboration
The VS Code [telemetry extension authors guide](https://code.visualstudio.com/api/extension-guides/telemetry) contains guidelines to collect and report telemetry data to [Azure Monitor and Application Insights](https://azure.microsoft.com/services/monitor/) from VS Code extensions. 

A few implementation details to be considered:
* Use the [@vscode/extension-telemetry](https://www.npmjs.com/package/@vscode/extension-telemetry) npm module since the telemetry data is reported to Azure Monitor and Application Insights
* Add a `telemetry.json` as recommended [here](https://code.visualstudio.com/api/extension-guides/telemetry#telemetry.json)

### Tasks
- [ ] Initialize the telemetry library on activating extension and add a `telemetry.json` file at the root of the `ide-extension` package and make it available in the `dist` folder - 0.5 day
- [ ] Add utility functions to send telemetry events - 2 days
- [ ] Add a new message and message handler to handle the click event of a tutorial card and trigger telemetry event - 2 days 
- [ ] Define test case -- 1 day
- [ ] Add unit tests
- [ ] Add a new dashboard with charts for the telemetry events - 1 day
