### ISSUE TITLE
TBI - Provide telemetry data for the blogs and  tags opened

### ISSUE THREAD

**Issue by cjbernal** [SAP/knowledge-hub-extension#36]
### Description (include screenshots)
In order to better understand the content our users access with knowledge hub, we should be able to see the blogs and blog tags opened by our users. A blog (and its tag) should only be recorded if the user clicks on the card and opens the blog in the browser. This will help us to better understand the topics that are of interest to our users.

No user data should be recorded.

### Architecture Elaboration
The VS Code [telemetry extension authors guide](https://code.visualstudio.com/api/extension-guides/telemetry) contains guidelines to collect and report telemetry data to [Azure Monitor and Application Insights](https://azure.microsoft.com/services/monitor/) from VS Code extensions. 

A few implementation details to be considered:
* Use the [@vscode/extension-telemetry](https://www.npmjs.com/package/@vscode/extension-telemetry) npm module since the telemetry data is reported to Azure Monitor and Application Insights
* Add a `telemetry.json` as recommended [here](https://code.visualstudio.com/api/extension-guides/telemetry#telemetry.json)

Note: This backlog item depends on tasks from #35

### Tasks
- [ ] Add a new message and message handler to handle the click event of a blog card and trigger telemetry event - 2 days 
- [ ] Define test case -- 1 day
- [ ] Add unit tests
- [ ] Add a new dashboard with charts for the telemetry events - 1 day
