### ISSUE TITLE
FEATURE - Provide search result sorting by date for the Blogs tab

### ISSUE THREAD

**Issue by cjbernal** [SAP/knowledge-hub-extension#67]
_As a **user searching for blogs related to my topic of interest**,
I want to **be able to sort the search results**,
so that I **can view either the latest or oldest blogs first**, depending on my needs._

### Description

_This feature would allow users to look for blogs that were published during certain time periods. If they want to view the latest and greatest on a certain topic, they can sort by "Newest first". If they want to see the first discussions on a particular topic, they can sort by "Oldest first"._

### Technical Design
_What modules need to be created or enhanced?_ 
_How would the functionality be exposed and how can it be consumed?_

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a search executed in the Blogs tab ...
**when** I click the sort button ...
**then** ... I will be provided with options for sorting my search results: "Newest first" and "oldest first"
and then the results will be sorted by my selection, with either the newest blogs relevant to my search being displayed first or the oldest blogs relevant to my search being displayed first.

### Notes
Something to consider: SAP Community currently allows for sorting by `Relevance` and `Last Updated`. If there are limitations to the blogs API, then we can start by using these two sort methods. But it would be nice to also allow `Oldest First` sort as well. 

### Tasks
- [ ] Add `Most Recent` button to re-sort results
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by cjbernal** [comment]
As this is present in the current version of Knowledge hub, closing this.
