### ISSUE TITLE
FEATURE - Introduce ability to save Favorites in Blogs and Tutorials tabs

### ISSUE THREAD

**Issue by cjbernal** [SAP/knowledge-hub-extension#86]
_As a **Knowledge Hub user**,
I want to **save blogs and tutorials that are interesting to me**,
so that I **read/use them later without having to search again**_

### Description

_Users may have articles or blogs they have discovered via Knowledge Hub that they wish to return to later -- either because they use the contents frequently or they didn't have time to start/finish the content. We can simplify their experience of finding the materials again by allowing users to save them as a "Favorite"._

### Technical Design
_What modules need to be created or enhanced?_ 
_How would the functionality be exposed and how can it be consumed?_

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have the blogs/tutorials tab open with content displayed
**when** I click the Favorites icon next to a blog/tutorial
**then** that piece of content will be saved in a favorites list to be referred to later.

**Given** I have previously saved contents for my Favorites list
**when** I click on the button/tab to open the Favorites list 
**then** a list of content that I have previously marked as a Favorite will be displayed.

**Given** I have the Favorites list open
**when** I click on content that has been saved in the Favorites list
**then** the content will open in the browser.

### Tasks
- [ ] Locally store blog post and tutorial IDs (extension storage)
- [ ] Get data from stored IDs and display in Favorites tab/section
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by gpeuc** [comment]
Alright, we have some general idea how this would work (little stars at various objects, and then we expose this later somewhere), but can we first get some tech confirmation that this would work?

We most likely need some local storage, where IDs are stored. Blog post ID, and Tutorial ID, and later we read them in the Favourites section, or something like that. But can we first get some confirmation that this works, and then we will go into UI of it?

**Comment by cjbernal** [comment]
@gpeuc We should wait for @eouin to confirm, but this was briefly discussed in team grooming -- we already locally store tags so that they are retained when the user reopens Knowledge Hub. But if there is something else we need to consider, Ed would definitely be the person for that :-)

**Comment by eouin** [comment]
@gpeuc At the moment we are saving an array of object made with id's and a description text. We can do the sane for favorite entries.
